### PR TITLE
che #14357 Adding build scripts for 'master', 'nightly', 'release' centOS CI jobs

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/eclipse/che/issues/14357

### What this PR does
- adding build scripts & `VERSION` file for newly created centOS CI jobs https://github.com/openshiftio/openshiftio-cico-jobs/pull/1073
- coping Dockerfile from `/dockerfiles/ci` back to the root 
- No cleanup, docs update is done in this PR

### Open Questions
- is it required to build `latest` version of the image or `nighly` will be enough?
- do we need to build `dev/Dockerfile` via CI (as I understand image produced by this Dockerfile is used in the `che-machine-exec` devfile[1])? do we need this `dockerfiles/dev/Dockerfile` in general? can't we reuse existing - https://quay.io/repository/eclipse/che-golang-1.12 ?

 [1] https://github.com/eclipse/che-machine-exec/blob/master/devfile.yaml#L34

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
> do we need to build dev/Dockerfile via CI (as I understand image produced by this Dockerfile is used in the che-machine-exec devfile[1])? do we need this dockerfiles/dev/Dockerfile in general? can't we reuse existing - https://quay.io/repository/eclipse/che-golang-1.12 ?

For development we need `dep` tool. https://quay.io/repository/eclipse/che-golang-1.12 doesn't contains this tool.

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr good point, but I suspect that any go developer need `Go dependency management tool`, and the images we ship with devfile-regsitry do not contain it. How can we fix this issue in the general way?

**Comment by AndrienkoAleksandr** [comment]
> I suspect that any go developer need Go dependency management tool

Actually `dep` tool it was experiment from Google and for now it become `deprecated`. Google from golang 1.11(if I remember correctly)  provided golang `modules` feature for managing dependencies. So, I believe in the feature we should use it and feature works from the box since golange 1.11. But I didn't investigate how to rework our codes to use it. And I am not sure that it will be easy, because  our code base uses a lot external dependencies which was not migrated to use golang modules.

> che-jwtproxy also requires dep and with the current approach in order to start dogfooding we would need to have the similar version of dockerfiles/dev in the https://github.com/eclipse/che-jwtproxy

I think you are right and we need to have some common dev image.

**Comment by ibuziuk** [comment]
> I think you are right and we need to have some common dev image.

@AndrienkoAleksandr do you happen to know if there is some official dev image with `dep` pre-installed ? smth similar to `maven:3.6.1-jdk-8` which contains not only runtime but also build tool. I believe this issue is very important to tackle in some generic way since it reveals the fact that our go images might be not good enough for development (which is a blocker for dogfooding)

**Comment by AndrienkoAleksandr** [comment]
> do you happen to know if there is some official dev image with dep pre-installed ? 

I tried to find such one, but I didn't find.

**Pull request merged**
