### PR TITLE
CRW-1594 add /bin/sleep to alpine and...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

CRW-1594 add /bin/sleep to alpine and /usr/bin/sleep to rhel image

Change-Id: I700e99125b564927c1cc82bcd8275a94a6ab8295
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1594

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
I don't know if this change is a good idea, and if it even works. I just validated that the sleep executable can be added to the scratch image... but could not RUN it locally (because it's a scratch image). So I don't know if Kubernetes Image Puller can pull and sleep this image. @ibuziuk WDYT of this idea? See https://issues.redhat.com/browse/CRW-1594 for request.

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by nickboldt** [comment]
Ilya said:
> yeah, looks good
> you can verify it by deploying KIP and specifying the image for pre-pulling

**Comment by nickboldt** [comment]
merged... follow up task will be to build nightly and see if KIP can pull it and invoke sleep on it

**Comment by nickboldt** [comment]
Image built as quay.io/eclipse/che-machine-exec:2f340f4 -> https://quay.io/repository/eclipse/che-machine-exec?tag=2f340f4&tab=tags

**Pull request merged**
