### PR TITLE
Do not provision everything from node:10.16-alpine into scratch

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Initially, it was supposed that there is not shell available in che-machine container.
But then by mistake, then was added the wrong usage of ARG because its value is not propagated during different stages of the multistage build. As result, everything from cloud-shell-builder was added into the scratch target image.

Also, initialization of user was fixed in the following way https://stackoverflow.com/questions/49955097/how-do-i-add-a-user-when-im-using-alpine-as-a-base-image/55757473#55757473

It's tested and the image is available by `sleshchenko/che-machine-exec:new-dockerfile`

:warning: rhel based docker image is not updated since Cloud Shell is not expected in CRW for now. Let me know if you have some concerts related to it.

P.S. Thank @AndrienkoAleksandr for helping me a lot in investigation cloud-shell related issues

### What does it fix?
https://github.com/eclipse/che/issues/16012
https://github.com/eclipse/che/issues/15888
https://github.com/eclipse/che/issues/15893

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
> Before making it ready to review I also plan to fix rhel based docker image.

CRW don't use cloud shell. So I think CRW hasn't got such an issue. So as for me it looks safely to merge it for 7.9.0.

**Comment by AndrienkoAleksandr** [comment]
@sleshchenko I think you accidentally applied extra lines 19-31 and it is duplication of lines 39-51. Remove them, please it is break docker build. All another changes are good, I tested.

**Comment by nickboldt** [comment]
Yes, there was some discussion of including cloud shell in CRW but not sure we have time to do so safely

**Comment by AndrienkoAleksandr** [comment]
Looks excellent, LGTM.

**Comment by nickboldt** [comment]
Note also that changes to Dockerfile have zero impact on CRW. Please make sure you're changes (if important) are also done in rhel.Dockerfile.

**Comment by sleshchenko** [comment]
> Also, we cannot do multistage builds in Brew with more than 2 stages (builder + resulting image), so having two different builders won't work for CRW.

I think the solution here could be separating cloud-shell and machine-exec dockerfiles:
1. Go binaries are build and added to stratch image, image is named che-machine-exec.
2. Cloud Shell Web App is built and added to che-machine-exec. image is named cloud-shell.

Each build has 2 stages.

**Pull request merged**
